/*
 * SudokuFX - Copyright © 2024-present SOFT64.FR Lob2018
 * Licensed under the MIT License (MIT).
 * See the full license at: https://github.com/Lob2018/SudokuFX?tab=License-1-ov-file#readme
 */
package fr.softsf.sudokufx.view.component.list;

import java.text.MessageFormat;
import java.util.Objects;
import java.util.function.Function;
import java.util.function.Supplier;
import javafx.beans.binding.StringBinding;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.ListCell;
import javafx.scene.control.ListView;
import javafx.scene.control.Tooltip;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Priority;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import fr.softsf.sudokufx.view.component.MyAlert;

/**
 * A reusable {@link ListCell} for displaying items of type {@code T} in a {@link ListView}.
 *
 * <p>Each cell shows a label with text generated by a {@link Function} and a remove button.
 * Accessible texts, tooltips, and confirmation messages are dynamically retrieved via {@link
 * java.util.function.Supplier}. When the remove button is pressed, a confirmation {@link
 * fr.softsf.sudokufx.view.component.MyAlert} is created and shown, allowing the user to confirm the
 * removal of the item.
 *
 * <p>The cell clears its content when empty to avoid memory leaks and ensure proper reuse.
 *
 * @param <T> the type of items displayed in the {@link ListView}
 */
public final class GenericDtoListCell<T> extends ListCell<T> {

    private static final Logger LOG = LoggerFactory.getLogger(GenericDtoListCell.class);

    private final HBox hBox = new HBox();
    private final Label label = new Label();
    private final Button button = new Button();

    private final ListView<T> listView;
    private final Function<T, String> displayTextFunction;

    private final Supplier<String> buttonAccessibleTextSupplier;
    private final Supplier<String> confirmationTitleSupplier;
    private final Supplier<String> confirmationMessageSupplier;

    /**
     * Constructs a new GenericDtoListCell.
     *
     * <p>The provided {@code StringBinding}s are internally converted to {@link Supplier<String>}
     * so that their values are evaluated when needed, avoiding memory leaks and keeping the
     * ListCell lightweight.
     *
     * @param listView the ListView containing this cell
     * @param buttonText the text displayed on the remove button
     * @param buttonAccessibleTextBinding binding to provide the button's accessible text
     *     (localized)
     * @param confirmationTitleBinding binding to provide the confirmation dialog title (localized)
     * @param confirmationMessageBinding binding to provide the confirmation dialog message
     *     (localized)
     * @param displayTextFunction function to generate the display text for each item
     */
    public GenericDtoListCell(
            ListView<T> listView,
            String buttonText,
            StringBinding buttonAccessibleTextBinding,
            StringBinding confirmationTitleBinding,
            StringBinding confirmationMessageBinding,
            Function<T, String> displayTextFunction) {
        this.listView = Objects.requireNonNull(listView);
        this.buttonAccessibleTextSupplier =
                () -> Objects.requireNonNull(buttonAccessibleTextBinding).get();
        this.confirmationTitleSupplier =
                () -> Objects.requireNonNull(confirmationTitleBinding).get();
        this.confirmationMessageSupplier =
                () -> Objects.requireNonNull(confirmationMessageBinding).get();
        this.displayTextFunction = Objects.requireNonNull(displayTextFunction);
        HBox.setHgrow(label, Priority.ALWAYS);
        hBox.setFocusTraversable(false);
        label.setFocusTraversable(true);
        button.setFocusTraversable(true);
        button.getStyleClass().addAll("material", "menuListLineButton");
        button.setText(buttonText);
        label.getStyleClass().addAll("root", "menuButtonLabel");
        hBox.getStyleClass().add("menuListLineContainer");
        hBox.getChildren().addAll(label, button);
    }

    /**
     * Updates the cell's content.
     *
     * <p>If the item is not null, sets the label text and button behavior. If empty, clears the
     * cell's content.
     *
     * @param item the item to display
     * @param empty whether this cell is empty
     */
    @Override
    protected void updateItem(T item, boolean empty) {
        super.updateItem(item, empty);
        if (empty || item == null) {
            setGraphic(null);
            setAccessibleText(null);
            button.setAccessibleText(null);
            button.setTooltip(null);
            button.setOnAction(null);
            label.setText(null);
        } else {
            String displayText = displayTextFunction.apply(item);
            label.setText(displayText);
            setGraphic(hBox);
            setAccessibleText(displayText);
            String buttonTextFormatted =
                    MessageFormat.format(buttonAccessibleTextSupplier.get(), displayText);
            button.setAccessibleText(buttonTextFormatted);
            button.setTooltip(new Tooltip(buttonTextFormatted));
            button.setOnAction(
                    event -> {
                        T currentItem = getItem();
                        if (currentItem != null) {
                            confirmAndRemoveItem(
                                    currentItem, displayTextFunction.apply(currentItem));
                        } else {
                            LOG.warn(
                                    "getItem() returned null in GenericDtoListCell button action.");
                        }
                    });
        }
    }

    /**
     * Displays a confirmation dialog and removes the item if the user confirms.
     *
     * @param item the item to remove
     */
    private void confirmAndRemoveItem(T item, String displayText) {
        MyAlert confirmationAlert = new MyAlert(Alert.AlertType.CONFIRMATION);
        confirmationAlert.setTitle(confirmationTitleSupplier.get());
        confirmationAlert.setHeaderText(null);
        Label content =
                new Label(MessageFormat.format(confirmationMessageSupplier.get(), displayText));
        confirmationAlert.getDialogPane().setContent(content);
        confirmationAlert
                .showAndWait()
                .ifPresent(
                        response -> {
                            if ("OK".equals(response.getText())) {
                                listView.getItems().remove(item);
                            }
                        });
    }
}
