name: OSV-Scanner Scheduled Scan

on:
  schedule:
    - cron: "0 13 * * 4"
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

permissions:
  actions: read
  security-events: write
  contents: read

jobs:
  scan-scheduled:
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@9a498708959aeaef5ef730655706c5a1df1edbc2" # v2.3.8
    with:
      scan-args: "--recursive=false --skip-git --skip-file=./requirements.txt --output-file=results.json"
